name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-24.04, macos-14, windows-latest]
        python-version: ['3.11', '3.13']
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -e .[tests,versions_pins_for_ci]

    - name: Run tests
      run: pytest --verbose --durations=10 -k "not sim_setups" -k "not clear_sky" -k "not lw_transport"